---
version: "2" 
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      argument-count:
      config:
        threshold: 4
      complex-logic:
        config:
          threshold: 4
      file-lines:
        config:
          threshold: 250
      method-complexity:
        config:
          threshold: 10
      method-count:
        config:
          threshold: 20
      method-lines:
        config:
          threshold: 50
      nested-control-flow:
        config:
          threshold: 4
      return-statements:
        config:
          threshold: 4
      Similar code:
        enabled: false
      Identical code:
        enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
- docs/
