swagger: "2.0"
info:
  description: |
    MangaDB allows you to easily keep track of the mangas you are reading,
    want to read, and have already finished reading.

    If you have any questions or want to contribute then [![Gitter](https://badges.gitter.im/Rafase282/Mangadb.svg)](https://gitter.im/Rafase282/Mangadb?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

    For this sample, you can use the api key `special-key` to test the authorization filters
  version: "1.0.0"
  title: MangaDB Swagger
  termsOfService: http://helloreverb.com/terms/
  contact:
    name: rafase282@gmail.com
  license:
    name: MIT
    url: https://github.com/Rafase282/Mangadb/blob/master/LICENSE
host: petstore.swagger.io
basePath: /v2
schemes:
  - https
consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: x-access-token
    in: header
paths:
  /auth:
    post:
      tags:
        - mangas
      summary: Creates User.
      description: "Handle manga requests"
      operationId: getToken
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: formData
          name: username
          description: Target username.
          required: true
          type: string
        - in: formData
          name: password
          description: Target username.
          required: true
          type: string
          format: password
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
  /mangas:
    get:
      tags:
        - mangas
        - admin
      summary: Get a list of all mangas on the database.
      description: "Handle manga requests"
      operationId: getAllMangas
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
  /mangas/{user}:
    get:
      tags:
        - mangas
      summary: Get a list of all mangas on the database for the specified user.
      description: "Handle manga requests"
      operationId: getAlluserMangas
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: path
          name: user
          description: Target username.
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
    post:
      tags:
        - mangas
      summary: Creates manga.
      description: "Handle manga requests"
      operationId: createmanga
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: path
          name: user
          description: Target username.
          required: true
          type: string
        - in: formData
          name: title
          description: Target username.
          required: true
          type: string
        - in: formData
          name: author
          description: Target username.
          required: true
          type: string
        - in: formData
          name: url
          description: Target username.
          required: true
          type: string
        - in: formData
          name: userStatus
          description: Target username.
          required: true
          type: string
        - in: formData
          name: type
          description: Target username.
          required: true
          type: string
        - in: formData
          name: categories
          description: Target username.
          required: true
          type: string
        - in: formData
          name: chapter
          description: Target username.
          required: true
          type: integer
          format: int32
        - in: formData
          name: seriesStatus
          description: Target username.
          required: true
          type: string
        - in: formData
          name: plot
          description: Target username.
          required: true
          type: string
        - in: formData
          name: altName
          description: Target username.
          required: true
          type: string
        - in: formData
          name: direction
          description: Target username.
          required: true
          type: string
        - in: formData
          name: thumbnail
          description: Target username.
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
    delete:
      tags:
        - mangas
      summary: Deletes mangas from target user
      description: "The passwords are encrypted."
      operationId: deleteMangasbyuser
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: path
          name: user
          description: Target username.
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
  /mangas/{user}/{title}:
    get:
      tags:
        - mangas
      summary: Get information on a specific user's managa by title.
      description: "Handle manga requests"
      operationId: getMangabyId
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: path
          name: user
          description: Target username.
          required: true
          type: string
        - in: path
          name: title
          description: Target manga title.
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
    put:
      tags:
        - mangas
      summary: Get information on a specific user's managa by title.
      description: "Handle manga requests"
      operationId: updateMangabyId
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: path
          name: user
          description: Target username.
          required: true
          type: string
        - in: path
          name: title
          description: Target manga title.
          required: true
          type: string

      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
    delete:
      tags:
        - mangas
      summary: Deletes target manga.
      description: "The passwords are encrypted."
      operationId: deleteUserbyUsername
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: path
          name: user
          description: Target username.
          required: true
          type: string
        - in: path
          name: title
          description: Target username.
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
  /users:
    get:
      tags:
        - users
        - admin
      summary: Get a list of all the users in the database.
      description: "Handle manga requests"
      operationId: getAllusers
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
    post:
      tags:
        - mangas
      summary: Creates User.
      description: "Handle manga requests"
      operationId: createuser
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: formData
          name: username
          description: Target username.
          required: true
          type: string
        - in: formData
          name: password
          description: Target username.
          required: true
          type: string
          format: password
        - in: formData
          name: email
          description: Target username.
          required: true
          type: string
        - in: formData
          name: firstname
          description: Target username.
          required: true
          type: string
        - in: formData
          name: lastname
          description: Target username.
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
    delete:
      tags:
        - users
      summary: Deletes all users.
      description: "The passwords are encrypted."
      operationId: deleteusers
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
  /users/{user}:
    get:
      tags:
        - users
      summary: Get specified user's data.
      description: "The passwords are encrypted."
      operationId: getUserbyUsername
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: path
          name: user
          description: Target username.
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
    put:
      tags:
        - users
      summary: Get information on a specific user's managa by title.
      description: "Handle manga requests"
      operationId: updateuser
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: path
          name: user
          description: Target username.
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
    delete:
      tags:
        - users
        - admin
      summary: Deletes target user.
      description: "The passwords are encrypted."
      operationId: deleteMangabyTitle
      parameters:
        - in: header
          name: x-access-token
          description: Base64 Encoded JSON Web Token
          required: true
          type: string
          default: xxxxx
        - in: path
          name: user
          description: Target username.
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
      security:
        - api_key: []
definitions:
  API_KEY:
    type: string
